import type { AppProps } from "next/app";
import Head from "next/head";

import Layout from "@/components/Layout";

import globalStyles from "../styles/GlobalStyles";

function App({ Component, pageProps }: AppProps) {
  globalStyles();

  return (
    <>
      <Head>
        <title>Mao De Matos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default App;
