import type { NextPage } from "next";
import Head from "next/head";
import tw from "twin.macro";

import { CustomImage } from "@/components/CustomImage";

const Home: NextPage = () => {
  const cards = [
    {
      title: "Documentation →",
      url: "https://nextjs.org/docs",
      content: "Find in-depth information about Next.js features and API.",
    },
    {
      title: "Learn →",
      url: "https://nextjs.org/learn",
      content: "Learn about Next.js in an interactive course with quizzes!",
    },
    {
      title: "Examples →",
      url: "https://github.com/vercel/next.js/tree/canary/examples",
      content: "Discover and deploy boilerplate example Next.js projects.",
    },
    {
      title: "Deploy →",
      url: "https://vercel.com/new",
      content:
        "Instantly deploy your Next.js site to a public URL with Vercel.",
    },
  ];

  return (
    <div tw="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main tw="min-h-screen py-8 px-16 flex flex-col flex-1 justify-center items-center gap-8">
        <h1 tw="text-6xl font-bold text-center">
          Welcome to{" "}
          <a href="https://nextjs.org" tw="text-blue-500 hocus:underline">
            Next.js
          </a>
          !
        </h1>

        <div tw="mockup-code light:(bg-transparent text-base-content border border-base-300)">
          {/* <div> */}
          <pre data-prefix="$">
            <code>Get started by editing</code>
          </pre>
          <pre data-prefix=">" tw="text-warning">
            {/* <pre data-prefix=">"> */}
            <code>pages/index.tsx</code>
          </pre>
        </div>

        <div tw="flex flex-col w-full sm:(w-auto flex-row) items-center justify-center flex-wrap max-w-3xl">
          {cards.map((element, idx) => (
            <a
              key={idx}
              href={element.url}
              tw="transition-colors m-4 p-6 text-left border border-base-300 rounded-xl max-w-xs hocus:(text-blue-500 border-blue-500)"
            >
              <h2 tw="mb-4 font-semibold text-2xl">{element.title}</h2>
              <p tw="text-xl">{element.content}</p>
            </a>
          ))}
        </div>
      </main>

      <footer tw="flex flex-1 py-8 justify-center items-center px-8 border-t border-t-base-200 dark:(border-base-300)">
        <div>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            tw="flex justify-center items-center grow"
          >
            Powered by{" "}
            <CustomImage
              src={"/vercel.svg"}
              alt="Vercel Logo"
              wrapperProps={{
                css: { ...tw`relative h-4 w-20 ml-2 dark:(invert)` },
              }}
            />
          </a>
        </div>
      </footer>
    </div>
  );
};

export default Home;
